server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: BIZ
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: logan123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

